# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - user-invoicing-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://registryforinvoicing.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8427d57f2f5e42eca8d38ea69e826152 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fde47ec12a42426caab0576d10dc6985 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: registryforinvoicing.azurecr.io/invoice-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'user-invoicing-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_33340a864b49449eb3203264c3692235 }}
        images: 'registryforinvoicing.azurecr.io/invoice-app:${{ github.sha }}'